name: sc-dandelion-container
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - seaborn
  - scikit-learn
  - statsmodels
  - numba
  - pytables
  - python-igraph
  - leidenalg
  - graph-tool>=2.77
  - pip
  - pytest
  - tbb
  - rpy2
  - r-base
  - r-stringi
  - r-optparse
  - r-tigger
  - r-shazam
  - r-airr
  - r-alakazam
  - igblast
  - blast
  - pip:
      - scanpy>=1.7.0
      - git+https://www.github.com/zktuong/dandelion.git
      - biopython
      - receptor-utils
