name: dandelion
channels:
- conda-forge
- bioconda
- anaconda
- defaults
dependencies:
- numpy
- pandas
- pandoc
- pyyaml
- changeo
- seaborn
- statsmodels
- numba
- pytables
- pytest
- pip
- tbb
- pip:
  - nbsphinx
  - sphinx-autodoc-typehints
  - rpy2>=3.4.0
  - pytest-cov
  - -r requirements.txt
  - git+https://www.github.com/zktuong/nxviz.git
  - scirpy
  - scrublet
  - annoy=1.16.3
