name: dandelion
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - numpy
  - pandas
  - pandoc
  - pyyaml
  - seaborn
  - statsmodels
  - pytables>=3.8.0
  - pytest
  - graph-tool
  - pip
  - tbb
  - pip:
      - numba
      - changeo
      - matplotlib
      - nbsphinx
      - sphinx-autodoc-typehints
      - annoy==1.16.3
      - rpy2>=3.4.2
      - pytest-cov
      - -r requirements.txt
      - scirpy
      - scrublet
