name: dandelion
channels:
  - conda-forge
  - bioconda
dependencies:
  - numpy
  - pandas
  - pandoc
  - pyyaml
  - seaborn
  - statsmodels
  - pytables>=3.8.0
  - pytest
  - graph-tool
  - r-shazam
  - r-alakazam
  - r-tigger
  - r-scoper
  - bioconductor-edger
  - pip
  - tbb
  - pip:
      - numba
      - changeo
      - matplotlib
      - nbsphinx
      - sphinx-autodoc-typehints
      - annoy==1.16.3
      - pytest-cov
      - scirpy
      - scrublet
      - . # This installs the current directory as a package
