name: dandelion
channels:
- conda-forge
- bioconda
- anaconda
- defaults
dependencies:
- python>=3.7,<=3.8
- numpy
- pandas
- pandoc
- pyyaml
- changeo
- adjustText
- distance
- joblib
- plotnine
- seaborn
- scikit-learn
- statsmodels
- numba
- pytables
- pytest
- mock
- pillow
- sphinx
- sphinx_rtd_theme
- pip
- pip:
  - nbsphinx
  - sphinx-autodoc-typehints
  - six
  - readthedocs-sphinx-ext
  - recommonmark
  - setuptools>=45
  - wheel
  - setuptools_scm[toml]>=6.0
  - numpy>=1.18.4
  - pandas>=1.0.3
  - changeo>=1.0.0
  - anndata>=0.7.1
  - scanpy>=1.4.6
  - distance>=0.1.3
  - joblib>=0.14.1
  - scikit-learn>=0.23.0
  - scikit-bio>=0.5.6
  - scipy>=1.4.1
  - numba>=0.48.0
  - seaborn>=0.10.1
  - networkx>=2.4
  - leidenalg>=0.8.0
  - plotnine>=0.6.0
  - polyleven>=0.5
  - h5py>=2.10.0,<3.0.0