name: dandelion
channels:
- conda-forge
- bioconda
- anaconda
- defaults
dependencies:
- python>=3.7,<=3.8
- pandoc
- pyyaml
- ipython_genutils
- adjustText
- statsmodels
- pytables
- pytest
- changeo
- airr
- mock
- pillow
- pip
- pip:
  - nbsphinx==0.8.6
  - sphinx==4.1.2
  - matplotlib<=3.5.3
  - sphinx_autodoc_typehints>=1.8.0
  - sphinx_rtd_theme>=0.4,<0.5
  - six
  - readthedocs-sphinx-ext
  - recommonmark
  - setuptools>=45
  - palantir
  - wheel
  - setuptools_scm[toml]>=6.0
  - numpy==1.23.5
  - pandas>=1.0.3,<1.5.0
  - anndata>=0.7.1
  - scanpy>=1.7.0
  - distance>=0.1.3
  - scikit-learn>=0.23.0
  - scipy>=1.4.1
  - numba>=0.48.0,<0.54.0
  - seaborn>=0.10.1
  - networkx>=2.4
  - leidenalg>=0.8.0
  - plotnine>=0.6.0
  - polyleven>=0.5
  - h5py>=2.10.0,<3.0.0
